// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.857
package template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func AdminEvents(deployment string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html lang=\"en\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = head("Edit Events", "admin_events.js", nil).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<body><div class=\"container-fluid\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = header(deployment).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = nav().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<h1 id=\"doc-title\">Edit Events</h1><p>For each event, you can configure permissions for individuals, positions, or teams. For example:</p><ul><li>person:Tool</li><li>position:007</li><li>team:Council</li></ul><p>You can also choose when each permission is valid:</p><ul><li>Always: valid all year long</li><li>On-Site: valid only when a matching Ranger is marked \"on-site\" in Clubhouse</li></ul><p><strong>The REQUIRE_ACTIVE flag is unused</strong>, replaced by \"on-site\" validity.</p><div class=\"row\" id=\"event_access_container\"><div class=\"col-sm-12 py-1 event_access\"><div class=\"card\"><label class=\"card-header\">Access for <span class=\"event_name\"></span> (<span class=\"access_mode\"></span>):</label><ul class=\"list-group list-group-small list-group-flush card-body\"><li class=\"list-group-item ps-3\"><select class=\"access_validity\" onchange=\"setValidity(this)\"><option value=\"always\">Always</option> <option value=\"onsite\">On-Site</option></select> <button class=\"badge btn btn-danger remove-badge float-end\" onclick=\"removeAccess(this)\">X</button></li></ul><div class=\"card-footer\"><label for=\"access_add\">Add:</label> <input id=\"access_add\" class=\"form-control input-sm auto-width\" type=\"text\" inputmode=\"verbatim\" placeholder=\"person:Tool\" onchange=\"addAccess(this)\"></div></div></div></div><div class=\"row\" id=\"event_new_container\"><div class=\"col-sm-12 event_access\"><label for=\"event_add\">Create New Event:</label> <input id=\"event_add\" class=\"form-control input-sm auto-width\" disabled=\"\" type=\"text\" inputmode=\"verbatim\" placeholder=\"Burn-A-Matic 3000\" onchange=\"addEvent(this)\"></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
