CREATE TABLE `person` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `first_name` varchar(25) NOT NULL,
    `mi` varchar(10) NOT NULL DEFAULT '',
    `last_name` varchar(25) NOT NULL,
    `callsign` varchar(64) NOT NULL,
    `street1` varchar(128) NOT NULL DEFAULT '',
    `street2` varchar(128) NOT NULL DEFAULT '',
    `apt` varchar(10) NOT NULL DEFAULT '',
    `city` varchar(50) NOT NULL DEFAULT '',
    `state` varchar(128) NOT NULL DEFAULT '',
    `zip` varchar(10) NOT NULL DEFAULT '',
    `country` varchar(25) NOT NULL DEFAULT '',
    `home_phone` varchar(25) NOT NULL DEFAULT '',
    `alt_phone` varchar(25) NOT NULL DEFAULT '',
    `email` varchar(50) DEFAULT NULL,
    `camp_location` varchar(200) NOT NULL DEFAULT '',
    `on_site` tinyint(1) NOT NULL DEFAULT 0,
    `vehicle_blacklisted` tinyint(1) NOT NULL DEFAULT 0,
    `date_verified` date DEFAULT NULL,
    `password` varchar(64) DEFAULT NULL,
    `created_at` datetime DEFAULT current_timestamp(),
    `has_note_on_file` tinyint(1) NOT NULL DEFAULT 0,
    `callsign_approved` tinyint(1) NOT NULL DEFAULT 0,
    `shirt_size` varchar(10) DEFAULT NULL,
    `status` enum('active','alpha','auditor','bonked','echelon','deceased','dismissed','inactive','inactive extension','past prospective','prospective','resigned','retired','suspended','uberbonked') NOT NULL,
    `status_date` date DEFAULT NULL,
    `tpassword` varchar(64) DEFAULT NULL,
    `tpassword_expire` int(11) DEFAULT NULL,
    `updated_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'Most recent modification time.',
    `shirt_style` varchar(32) DEFAULT NULL,
    `gender_custom` varchar(32) DEFAULT NULL,
    `bpguid` varchar(64) DEFAULT NULL,
    `sfuid` varchar(64) DEFAULT NULL,
    `emergency_contact` mediumtext DEFAULT NULL,
    `vintage` tinyint(1) DEFAULT 0,
    `sms_off_playa` varchar(255) DEFAULT NULL,
    `sms_on_playa` varchar(255) DEFAULT NULL,
    `sms_off_playa_stopped` tinyint(1) NOT NULL DEFAULT 0,
    `sms_on_playa_stopped` tinyint(1) NOT NULL DEFAULT 0,
    `sms_off_playa_verified` tinyint(1) NOT NULL DEFAULT 0,
    `sms_on_playa_verified` tinyint(1) NOT NULL DEFAULT 0,
    `sms_off_playa_code` varchar(16) DEFAULT NULL,
    `sms_on_playa_code` varchar(16) DEFAULT NULL,
    `timesheet_confirmed` tinyint(1) NOT NULL DEFAULT 0,
    `timesheet_confirmed_at` datetime DEFAULT NULL,
    `callsign_normalized` varchar(128) NOT NULL,
    `callsign_soundex` varchar(128) NOT NULL,
    `message` mediumtext DEFAULT NULL,
    `message_updated_at` datetime DEFAULT NULL,
    `behavioral_agreement` tinyint(1) NOT NULL DEFAULT 0,
    `callsign_pronounce` varchar(200) DEFAULT NULL,
    `logged_in_at` timestamp NULL DEFAULT NULL,
    `last_seen_at` timestamp NULL DEFAULT NULL,
    `person_photo_id` bigint(20) DEFAULT NULL,
    `known_rangers` text DEFAULT NULL,
    `known_pnvs` text DEFAULT NULL,
    `lms_id` varchar(191) DEFAULT NULL,
    `reviewed_pi_at` datetime DEFAULT NULL,
    `pronouns` enum('','female','male','neutral','custom') NOT NULL DEFAULT '',
    `pronouns_custom` varchar(191) NOT NULL,
    `pi_reviewed_for_dashboard_at` datetime DEFAULT NULL,
    `lms_username` varchar(191) DEFAULT NULL,
    `is_bouncing` tinyint(1) NOT NULL DEFAULT 0,
    `tshirt_swag_id` int(11) DEFAULT NULL,
    `tshirt_secondary_swag_id` int(11) DEFAULT NULL,
    `long_sleeve_swag_id` int(11) DEFAULT NULL,
    `vanity_changed_at` datetime DEFAULT NULL,
    `used_vanity_change` tinyint(1) NOT NULL DEFAULT 0,
    `employee_id` varchar(255) DEFAULT NULL,
    `gender_identity` enum('cis-female','cis-male','custom','female','fluid','male','','non-binary','queer','trans-female','trans-male','two-spirit') NOT NULL DEFAULT '',
    `preferred_name` varchar(255) NOT NULL DEFAULT '',
    `years_seen` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`years_seen`)),
    `years_as_contributor` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`years_as_contributor`)),
    `years_as_ranger` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`years_as_ranger`)),
    `years_combined` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`years_combined`)),
    PRIMARY KEY (`id`),
    UNIQUE KEY `callsign` (`callsign`),
    UNIQUE KEY `email` (`email`),
    KEY `person_callsign_normalized_index` (`callsign_normalized`),
    KEY `person_callsign_soundex_index` (`callsign_soundex`),
    KEY `person_lms_id_index` (`lms_id`),
    KEY `person_status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;