CREATE TABLE `person` (
    `id` bigint(20) NOT NULL AUTO_INCREMENT,
    `first_name` varchar(25) NOT NULL,
    `mi` varchar(10) NOT NULL DEFAULT '',
    `last_name` varchar(25) NOT NULL,
    `callsign` varchar(64) NOT NULL,
    `street1` varchar(128) NOT NULL DEFAULT '',
    `street2` varchar(128) NOT NULL DEFAULT '',
    `apt` varchar(10) NOT NULL DEFAULT '',
    `city` varchar(50) NOT NULL DEFAULT '',
    `state` varchar(128) NOT NULL DEFAULT '',
    `zip` varchar(10) NOT NULL DEFAULT '',
    `country` varchar(25) NOT NULL DEFAULT '',
    `home_phone` varchar(25) NOT NULL DEFAULT '',
    `alt_phone` varchar(25) NOT NULL DEFAULT '',
    `email` varchar(50) DEFAULT NULL,
    `camp_location` varchar(200) NOT NULL DEFAULT '',
    `on_site` tinyint(1) NOT NULL DEFAULT 0,
    `vehicle_blacklisted` tinyint(1) NOT NULL DEFAULT 0,
    `date_verified` date DEFAULT NULL,
    `password` varchar(64) DEFAULT NULL,
    `created_at` datetime DEFAULT current_timestamp(),
    `has_note_on_file` tinyint(1) NOT NULL DEFAULT 0,
    `callsign_approved` tinyint(1) NOT NULL DEFAULT 0,
    `shirt_size` varchar(10) DEFAULT NULL,
    `status` enum('active','alpha','auditor','bonked','echelon','deceased','dismissed','inactive','inactive extension','past prospective','prospective','resigned','retired','suspended','uberbonked') NOT NULL,
    `status_date` date DEFAULT NULL,
    `tpassword` varchar(64) DEFAULT NULL,
    `tpassword_expire` int(11) DEFAULT NULL,
    `updated_at` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'Most recent modification time.',
    `shirt_style` varchar(32) DEFAULT NULL,
    `gender_custom` varchar(32) DEFAULT NULL,
    `bpguid` varchar(64) DEFAULT NULL,
    `sfuid` varchar(64) DEFAULT NULL,
    `emergency_contact` mediumtext DEFAULT NULL,
    `vintage` tinyint(1) DEFAULT 0,
    `sms_off_playa` varchar(255) DEFAULT NULL,
    `sms_on_playa` varchar(255) DEFAULT NULL,
    `sms_off_playa_stopped` tinyint(1) NOT NULL DEFAULT 0,
    `sms_on_playa_stopped` tinyint(1) NOT NULL DEFAULT 0,
    `sms_off_playa_verified` tinyint(1) NOT NULL DEFAULT 0,
    `sms_on_playa_verified` tinyint(1) NOT NULL DEFAULT 0,
    `sms_off_playa_code` varchar(16) DEFAULT NULL,
    `sms_on_playa_code` varchar(16) DEFAULT NULL,
    `timesheet_confirmed` tinyint(1) NOT NULL DEFAULT 0,
    `timesheet_confirmed_at` datetime DEFAULT NULL,
    `callsign_normalized` varchar(128) NOT NULL,
    `callsign_soundex` varchar(128) NOT NULL,
    `message` mediumtext DEFAULT NULL,
    `message_updated_at` datetime DEFAULT NULL,
    `behavioral_agreement` tinyint(1) NOT NULL DEFAULT 0,
    `callsign_pronounce` varchar(200) DEFAULT NULL,
    `logged_in_at` timestamp NULL DEFAULT NULL,
    `last_seen_at` timestamp NULL DEFAULT NULL,
    `person_photo_id` bigint(20) DEFAULT NULL,
    `known_rangers` text DEFAULT NULL,
    `known_pnvs` text DEFAULT NULL,
    `lms_id` varchar(191) DEFAULT NULL,
    `reviewed_pi_at` datetime DEFAULT NULL,
    `pronouns` enum('','female','male','neutral','custom') NOT NULL DEFAULT '',
    `pronouns_custom` varchar(191) NOT NULL,
    `pi_reviewed_for_dashboard_at` datetime DEFAULT NULL,
    `lms_username` varchar(191) DEFAULT NULL,
    `is_bouncing` tinyint(1) NOT NULL DEFAULT 0,
    `tshirt_swag_id` int(11) DEFAULT NULL,
    `tshirt_secondary_swag_id` int(11) DEFAULT NULL,
    `long_sleeve_swag_id` int(11) DEFAULT NULL,
    `vanity_changed_at` datetime DEFAULT NULL,
    `used_vanity_change` tinyint(1) NOT NULL DEFAULT 0,
    `employee_id` varchar(255) DEFAULT NULL,
    `gender_identity` enum('cis-female','cis-male','custom','female','fluid','male','','non-binary','queer','trans-female','trans-male','two-spirit') NOT NULL DEFAULT '',
    `preferred_name` varchar(255) NOT NULL DEFAULT '',
    `years_seen` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`years_seen`)),
    `years_as_contributor` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`years_as_contributor`)),
    `years_as_ranger` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`years_as_ranger`)),
    `years_combined` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`years_combined`)),
    PRIMARY KEY (`id`),
    UNIQUE KEY `callsign` (`callsign`),
    UNIQUE KEY `email` (`email`),
    KEY `person_callsign_normalized_index` (`callsign_normalized`),
    KEY `person_callsign_soundex_index` (`callsign_soundex`),
    KEY `person_lms_id_index` (`lms_id`),
    KEY `person_status_index` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `position` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `title` varchar(40) NOT NULL,
    `new_user_eligible` tinyint(1) NOT NULL DEFAULT 0,
    `all_rangers` tinyint(1) NOT NULL DEFAULT 0,
    `count_hours` tinyint(1) NOT NULL DEFAULT 1,
    `min` int(10) NOT NULL DEFAULT 1 COMMENT 'Min suggested Rangers per slot',
    `max` int(10) DEFAULT NULL COMMENT 'Max suggested Rangers per slot',
    `on_sl_report` tinyint(1) DEFAULT NULL,
    `on_trainer_report` tinyint(1) NOT NULL DEFAULT 0,
    `short_title` varchar(6) DEFAULT NULL,
    `type` varchar(32) DEFAULT NULL,
    `training_position_id` bigint(20) unsigned DEFAULT NULL,
    `contact_email` varchar(200) DEFAULT NULL,
    `prevent_multiple_enrollments` tinyint(1) NOT NULL DEFAULT 0,
    `active` tinyint(1) NOT NULL DEFAULT 1,
    `alert_when_empty` tinyint(1) NOT NULL DEFAULT 0,
    `team_id` int(11) DEFAULT NULL,
    `require_training_for_roles` tinyint(1) NOT NULL DEFAULT 0,
    `team_category` enum('public','all_members','optional') NOT NULL DEFAULT 'public',
    `alert_when_becomes_empty` tinyint(1) NOT NULL DEFAULT 0,
    `alert_when_no_trainers` tinyint(1) NOT NULL DEFAULT 0,
    `paycode` varchar(255) DEFAULT NULL,
    `resource_tag` varchar(255) DEFAULT NULL,
    `deselect_on_team_join` tinyint(1) NOT NULL DEFAULT 0,
    `no_payroll_hours_adjustment` tinyint(1) NOT NULL DEFAULT 0,
    `no_training_required` tinyint(1) NOT NULL DEFAULT 0,
    `auto_sign_out` tinyint(1) NOT NULL DEFAULT 0,
    `sign_out_hour_cap` double(8,2) NOT NULL DEFAULT 0.00,
    `mvr_eligible` tinyint(1) NOT NULL DEFAULT 0,
    `pvr_eligible` tinyint(1) NOT NULL DEFAULT 0,
    `parent_position_id` int(11) DEFAULT NULL,
    `not_timesheet_eligible` tinyint(1) NOT NULL DEFAULT 0,
    `cruise_direction` tinyint(1) NOT NULL DEFAULT 0,
    `mvr_signup_eligible` tinyint(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    KEY `position_mvr_eligible_index` (`mvr_eligible`),
    KEY `position_pvr_eligible_index` (`pvr_eligible`),
    KEY `position_parent_position_id_index` (`parent_position_id`),
    KEY `position_cruise_direction_index` (`cruise_direction`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci;

CREATE TABLE `person_position` (
    `person_id` bigint(20) unsigned NOT NULL,
    `position_id` bigint(20) unsigned NOT NULL,
    PRIMARY KEY (`person_id`,`position_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_unicode_ci COMMENT='links person to position';

CREATE TABLE `team` (
    `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `title` varchar(255) NOT NULL,
    `type` varchar(255) NOT NULL DEFAULT 'team',
    `active` tinyint(1) NOT NULL DEFAULT 1,
    `created_at` timestamp NULL DEFAULT NULL,
    `updated_at` timestamp NULL DEFAULT NULL,
    `mvr_eligible` tinyint(1) NOT NULL DEFAULT 0,
    `pvr_eligible` tinyint(1) NOT NULL DEFAULT 0,
    `email` varchar(255) DEFAULT NULL,
    `description` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `team_mvr_eligible_index` (`mvr_eligible`),
    KEY `team_pvr_eligible_index` (`pvr_eligible`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE `person_team` (
   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
   `person_id` int(11) NOT NULL,
   `team_id` int(11) NOT NULL,
   `created_at` timestamp NULL DEFAULT NULL,
   `updated_at` timestamp NULL DEFAULT NULL,
   PRIMARY KEY (`id`),
   UNIQUE KEY `person_team_person_id_team_id_unique` (`person_id`,`team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;